# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

openFileHandleRead <- function(filepath) {
    .Call(`_EigenH5_openFileHandleRead`, filepath)
}

closeFileHandle <- function(fh) {
    .Call(`_EigenH5_closeFileHandle`, fh)
}

start_blosc <- function() {
    invisible(.Call(`_EigenH5_start_blosc`))
}

check_blosc <- function() {
    .Call(`_EigenH5_check_blosc`)
}

is_transposed <- function(filename, groupname, dataname) {
    .Call(`_EigenH5_is_transposed`, filename, groupname, dataname)
}

mach2h5 <- function(dosagefile, h5file, datapath, snp_idx, names, p, options) {
    invisible(.Call(`_EigenH5_mach2h5`, dosagefile, h5file, datapath, snp_idx, names, p, options))
}

open_file_ro <- function(filename) {
    .Call(`_EigenH5_open_file_ro`, filename)
}

open_file_rw <- function(filename) {
    .Call(`_EigenH5_open_file_rw`, filename)
}

release_file <- function(p) {
    invisible(.Call(`_EigenH5_release_file`, p))
}

release_dataset <- function(p) {
    invisible(.Call(`_EigenH5_release_dataset`, p))
}

release_group <- function(p) {
    invisible(.Call(`_EigenH5_release_group`, p))
}

get_file_object <- function(f, object_name) {
    .Call(`_EigenH5_get_file_object`, f, object_name)
}

get_dataset <- function(f, object_name) {
    .Call(`_EigenH5_get_dataset`, f, object_name)
}

get_group <- function(f, object_name) {
    .Call(`_EigenH5_get_group`, f, object_name)
}

len <- function(x) {
    .Call(`_EigenH5_len`, x)
}

permutation_order <- function(options, dims) {
    .Call(`_EigenH5_permutation_order`, options, dims)
}

read_vector <- function(filename, datapath, options) {
    .Call(`_EigenH5_read_vector`, filename, datapath, options)
}

read_matrix <- function(filename, datapath, options) {
    .Call(`_EigenH5_read_matrix`, filename, datapath, options)
}

update_matrix <- function(data, filename, datapath, options) {
    .Call(`_EigenH5_update_matrix`, data, filename, datapath, options)
}

update_vector <- function(data, filename, datapath, options) {
    .Call(`_EigenH5_update_vector`, data, filename, datapath, options)
}

write_attribute_h5 <- function(filename, datapath, data) {
    .Call(`_EigenH5_write_attribute_h5`, filename, datapath, data)
}

read_attribute_h5 <- function(filename, datapath) {
    .Call(`_EigenH5_read_attribute_h5`, filename, datapath)
}

create_dataset_h5 <- function(filename, datapath, data, options) {
    .Call(`_EigenH5_create_dataset_h5`, filename, datapath, data, options)
}

link_objects_h5 <- function(filename_from, filename_to, datapath_from, datapath_to) {
    invisible(.Call(`_EigenH5_link_objects_h5`, filename_from, filename_to, datapath_from, datapath_to))
}

create_file_h5 <- function(filename) {
    invisible(.Call(`_EigenH5_create_file_h5`, filename))
}

norm_file <- function(filename) {
    .Call(`_EigenH5_norm_file`, filename)
}

dataset_chunks <- function(filename, datapath) {
    .Call(`_EigenH5_dataset_chunks`, filename, datapath)
}

extend_dataset <- function(filename, datapath, newdims) {
    invisible(.Call(`_EigenH5_extend_dataset`, filename, datapath, newdims))
}

extend_dataset_by <- function(filename, datapath, newdims) {
    invisible(.Call(`_EigenH5_extend_dataset_by`, filename, datapath, newdims))
}

get_datset_filter <- function(filename, datapath) {
    .Call(`_EigenH5_get_datset_filter`, filename, datapath)
}

guess_chunks <- function(dimsize) {
    .Call(`_EigenH5_guess_chunks`, dimsize)
}

exists_h5 <- function(filename, groupname = "/", dataname = "") {
    .Call(`_EigenH5_exists_h5`, filename, groupname, dataname)
}

isObject <- function(filename, dataname) {
    .Call(`_EigenH5_isObject`, filename, dataname)
}

isDataSet <- function(filename, dataname) {
    .Call(`_EigenH5_isDataSet`, filename, dataname)
}

isGroup <- function(filename, dataname) {
    .Call(`_EigenH5_isGroup`, filename, dataname)
}

ls_h5 <- function(filename, groupname = as.character( c("/")), full_names = FALSE) {
    .Call(`_EigenH5_ls_h5`, filename, groupname, full_names)
}

typeof_h5 <- function(filename, datapath) {
    .Call(`_EigenH5_typeof_h5`, filename, datapath)
}

file_acc_ct <- function(filename) {
    .Call(`_EigenH5_file_acc_ct`, filename)
}

dim_h5 <- function(filename, datapath) {
    .Call(`_EigenH5_dim_h5`, filename, datapath)
}

concat_mats <- function(newfile, newpath, selections, margin = 0L) {
    invisible(.Call(`_EigenH5_concat_mats`, newfile, newpath, selections, margin))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_EigenH5_RcppExport_registerCCallable', PACKAGE = 'EigenH5')
})
